import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


const poppinsRegular = localFont({
  src: "./fonts/Poppins-Regular.woff",
  variable: "--font-poppins-regular",
  weight: "400"
});
const poppinsBold = localFont({
  src: "./fonts/Poppins-Bold.woff",
  variable: "--font-poppins-bold",
  weight: "700"
})
const poppinsSemibold = localFont({
  src: "./fonts/Poppins-SemiBold.woff",
  variable: "--font-poppins-semibold",
  weight: "600"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${poppinsRegular.variable} ${poppinsBold.variable} ${poppinsSemibold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
